export type Crop={id:string;name:string;culture:string;area:number;soil:string;irrigation:string;planted:string;phase:string;moisture:number;capacity:number};
export type Event={id:string;date:string;type:string;plot:string;result:string};
export type State={crops:Crop[];active:string;water:number;automatic:boolean;history:Event[];read:string[];operation?:{kind:'pump'|'irrigation';startWater:number;plot:string}};
export const initial:State={crops:[{id:'1',name:'Talhão 01',culture:'Tomate',area:500,soil:'Franco-argiloso',irrigation:'Gotejamento',planted:'2026-07-12',phase:'Produção',moisture:37,capacity:2000},{id:'2',name:'Talhão 02',culture:'Pimentão',area:350,soil:'Franco-argiloso',irrigation:'Gotejamento',planted:'2026-07-20',phase:'Crescimento',moisture:54,capacity:2000},{id:'3',name:'Talhão 03',culture:'Alface',area:200,soil:'Arenoso',irrigation:'Microaspersão',planted:'2026-08-25',phase:'Crescimento',moisture:29,capacity:2000}],active:'1',water:1360,automatic:false,read:[],history:[{id:'h1',date:'2026-09-17',type:'Bombeamento',plot:'Reservatório',result:'+720 L'},{id:'h2',date:'2026-09-17',type:'Irrigação',plot:'Tomate — Talhão 01',result:'1.100 L'},{id:'h3',date:'2026-09-16',type:'Irrigação',plot:'Pimentão — Talhão 02',result:'780 L'},{id:'h4',date:'2026-09-15',type:'Chuva',plot:'Propriedade',result:'8 mm'}]};
export const n=(v:number)=>Math.round(v).toLocaleString('pt-BR');
export function plan(s:State,rain=10){const c=s.crops.find(c=>c.id===s.active)!;const needed=c.moisture<40&&rain<40;const rate:Record<string,number>={Tomate:2.2,Pimentão:2,Alface:1.8,Morango:2,Milho:2.5,Feijão:1.9};const volume=needed?Math.round(c.area*(rate[c.culture]||2.2)):0;const shortage=Math.max(0,volume-s.water);const pump=needed?Math.max(0,Math.min(1400,Math.min(c.capacity,volume+900)-s.water)):0;const limited=volume>c.capacity||volume>s.water+pump||volume/26.2>120;return {needed,volume,shortage,pump,limited,minutes:Math.ceil(volume/26.2),pumpMinutes:Math.ceil(pump/400*60),rain,c};}
export function event(s:State,type:string,plot:string,result:string):State{return {...s,history:[{id:crypto.randomUUID(),date:'2026-09-17',type,plot,result},...s.history]};}
export function pumpTick(s:State,amount=20):State{const c=s.crops.find(c=>c.id===s.active)!;return {...s,water:Math.min(c.capacity,s.water+amount)};}
export function irrigationTick(s:State,amount=50,target=65):State{const c=s.crops.find(c=>c.id===s.active)!;const used=Math.max(0,Math.min(s.water,amount,(target-c.moisture)/19*(c.area*2.2)));return {...s,water:Math.max(0,Number((s.water-used).toFixed(8))),crops:s.crops.map(x=>x.id===c.id?{...x,moisture:Math.min(target,Number((x.moisture+used/(c.area*2.2)*19).toFixed(8)))}:x)};}
