import assert from 'node:assert/strict';
import {initial,plan,pumpTick,irrigationTick,event} from '../app/model.ts';
const baseline=structuredClone(initial);
assert.equal(plan(baseline).volume,1100);
assert.equal(plan(baseline).pump,640);
assert.equal(plan(baseline).pumpMinutes,96);
assert.equal(plan(baseline,75).needed,false);
assert.equal(plan({...baseline,active:'2'}).needed,false);
assert.equal(pumpTick({...baseline,water:1990}).water,2000);
assert.equal(irrigationTick({...baseline,water:10},50).water,0);
assert.equal(irrigationTick({...baseline,water:0}).crops[0].moisture,37);
let cycle={...baseline,water:500};
for(let i=0;i<13;i++)cycle=pumpTick(cycle,100);
assert.equal(cycle.water,1800);
for(let i=0;i<11;i++)cycle=irrigationTick(cycle,100);
assert.equal(cycle.water,700);
assert.ok(Math.abs(cycle.crops[0].moisture-56)<1e-6);
assert.equal(cycle.crops[1].moisture,54);
const oversized={...baseline,crops:baseline.crops.map(c=>({...c,area:50000}))};
assert.equal(plan(oversized).limited,true);
assert.ok(plan(oversized).pumpMinutes<=210);
const log=event(cycle,'Irrigação','Tomate — Talhão 01','1.100 L');
assert.equal(log.history.length,baseline.history.length+1);
assert.equal(log.history[0].result,'1.100 L');
assert.deepEqual(initial,baseline);
console.log('ATLAS: 15 verificações aprovadas — balanço hídrico, janela solar, chuva, limites, ciclo e histórico.');
